name: Build ExampleMod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 8

    - name: Make Gradlew executable
      run: chmod +x ./gradlew

    - name: Place Minecraft 1.7.10 jar
      run: |
        mkdir -p ~/.gradle/caches/minecraft/net/minecraft/minecraft/1.7.10
        cp ./1.7.10.jar ~/.gradle/caches/minecraft/net/minecraft/minecraft/1.7.10/minecraft-1.7.10.jar

    - name: Build Mod
      run: ./gradlew build -Dfml.doDownload=false

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: examplemod
        path: build/libs/*.jar
